ci: create kubeconfig folder?

diff --git a/.github/workflows/kitchen-tests.yml b/.github/workflows/kitchen-tests.yml
--- a/.github/workflows/kitchen-tests.yml
+++ b/.github/workflows/kitchen-tests.yml
@@ -124,48 +124,48 @@ jobs:
       env:
         JUPYTERHUB_TLS_CER: ${{ secrets.JUPYTERHUB_TLS_CER }}
         JUPYTERHUB_TLS_KEY: ${{ secrets.JUPYTERHUB_TLS_KEY }}
+    - name: Create /tmp/kube_config
+      run: |
+        mkdir -p /tmp/kube_config
     - name: Authorize service account
       run: gcloud auth activate-service-account ${{ secrets.GCP_PF_SA }} --key-file=/tmp/credentials.json
       env:
         KUBECONFIG: /tmp/kube_config
         KUBE_CONFIG_PATH: /tmp/kube_config
-    - name: Check contents of /tmp
+    - name: Run Kitchen
+      run: kitchen test
+      env:
+        TF_VAR_billing_account: ${{ secrets.GCP_BILLING_ACCOUNT }}
+        TF_VAR_org_id: ${{ secrets.GCP_ORG_ID }}
+        TF_VAR_folder_id: ${{ secrets.GCP_CCV_CI_FOLDER_ID }}
+        INFOBLOX_USERNAME: ${{ secrets.INFOBLOX_JHUB_USER }}
+        INFOBLOX_PASSWORD: ${{ secrets.INFOBLOX_JHUB_PSWD }}
+        INFOBLOX_SERVER: ${{secrets.INFOBLOX_JHUB_HOST}}
+        TF_VAR_site_certificate_file: /tmp/tls.cer
+        TF_VAR_site_certificate_key_file: /tmp/tls.key
+        GOOGLE_APPLICATION_CREDENTIALS: /tmp/credentials.json
+        KUBECONFIG: /tmp/kube_config
+        KUBE_CONFIG_PATH: /tmp/kube_config
+    - name: Clean kitchen and terraform files
       run: |
-        ls -la /tmp
-  #   - name: Run Kitchen
-  #     run: kitchen test
-  #     env:
-  #       TF_VAR_billing_account: ${{ secrets.GCP_BILLING_ACCOUNT }}
-  #       TF_VAR_org_id: ${{ secrets.GCP_ORG_ID }}
-  #       TF_VAR_folder_id: ${{ secrets.GCP_CCV_CI_FOLDER_ID }}
-  #       INFOBLOX_USERNAME: ${{ secrets.INFOBLOX_JHUB_USER }}
-  #       INFOBLOX_PASSWORD: ${{ secrets.INFOBLOX_JHUB_PSWD }}
-  #       INFOBLOX_SERVER: ${{secrets.INFOBLOX_JHUB_HOST}}
-  #       TF_VAR_site_certificate_file: /tmp/tls.cer
-  #       TF_VAR_site_certificate_key_file: /tmp/tls.key
-  #       GOOGLE_APPLICATION_CREDENTIALS: /tmp/credentials.json
-  #       KUBECONFIG: /tmp/kube_config
-  #       KUBE_CONFIG_PATH: /tmp/kube_config
-  #   - name: Clean kitchen and terraform files
-  #     run: |
-  #       rm -rf .kitchen
-  #       rm -rf examples/*/.terraform
-  #       rm -rf examples/*/terraform.tfstate*
-  #   - name: Post-check dirty dirs in self-hosted
-  #     run: |
-  #       ls -la .
-  #       ls -la examples/sample-jhub
-  #       ls -la examples/sample-jhub-nfs
-  #       ls -la ~
+        rm -rf .kitchen
+        rm -rf examples/*/.terraform
+        rm -rf examples/*/terraform.tfstate*
+    - name: Post-check dirty dirs in self-hosted
+      run: |
+        ls -la .
+        ls -la examples/sample-jhub
+        ls -la examples/sample-jhub-nfs
+        ls -la ~
   
-  # # Clean up dangling images in self-hosted runner to avoid filling up docker disk 
-  # docker-cleanup:
-  #   needs: [test]
-  #   runs-on: self-hosted 
-  #   steps:
-  #   - name: Clean up docker images
-  #     run: |
-  #       docker images --filter=reference='brownccv/kitchen-terraform'
-  #       docker images --filter=reference='brownccv/kitchen-terraform' --filter "dangling=true" | grep -E "brownccv/kitchen-terraform" | awk '{ print $3 }' | xargs docker rmi || :
-  #       echo "After cleanup"
-  #       docker images --filter=reference='brownccv/kitchen-terraform'
+  # Clean up dangling images in self-hosted runner to avoid filling up docker disk 
+  docker-cleanup:
+    needs: [test]
+    runs-on: self-hosted 
+    steps:
+    - name: Clean up docker images
+      run: |
+        docker images --filter=reference='brownccv/kitchen-terraform'
+        docker images --filter=reference='brownccv/kitchen-terraform' --filter "dangling=true" | grep -E "brownccv/kitchen-terraform" | awk '{ print $3 }' | xargs docker rmi || :
+        echo "After cleanup"
+        docker images --filter=reference='brownccv/kitchen-terraform'
