ci: find pwd

diff --git a/.github/workflows/kitchen-tests.yml b/.github/workflows/kitchen-tests.yml
--- a/.github/workflows/kitchen-tests.yml
+++ b/.github/workflows/kitchen-tests.yml
@@ -16,7 +16,7 @@ env:
   USE_GKE_GCLOUD_AUTH_PLUGIN: true
   GOOGLE_APPLICATION_CREDENTIALS: /tmp/credentials.json
   KUBE_CONFIG_PATH: ~/.kube/config
-  
+
 jobs:
   docker:
     runs-on: ubuntu-latest
@@ -98,75 +98,76 @@ jobs:
         ls -la examples/sample-jhub
         ls -la examples/sample-jhub-nfs
         kubectl config view
-    - name: Remove Kitchen File
-      run: |
-        rm -rf .kitchen
-        rm -rf .terraform
-        rm -rf examples/*/.terraform
-        rm -rf examples/*/terraform.tfstate*
-        rm -f ~/.kube/config
-        ls -la ~/.kube || :
-    - name: Post-check dirty dirs in self-hosted
-      run: |
-        ls -la ~
-        ls -la .
-        ls -la examples/sample-jhub
-        ls -la examples/sample-jhub-nfs
-    - name: Create Credential File
-      run: |
-        echo "$GCP_CREDENTIAL_JSON" | base64 -d > /tmp/credentials.json
-      env:
-        GCP_CREDENTIAL_JSON: ${{ secrets.GCP_CREDENTIAL_JSON}}
-    - name: Create TLS Files
-      run: |
-        echo "$JUPYTERHUB_TLS_CER" > /tmp/tls.cer
-        echo "$JUPYTERHUB_TLS_KEY" > /tmp/tls.key
-      env:
-        JUPYTERHUB_TLS_CER: ${{ secrets.JUPYTERHUB_TLS_CER }}
-        JUPYTERHUB_TLS_KEY: ${{ secrets.JUPYTERHUB_TLS_KEY }}
-    - name: Authorize service account
-      run: | 
-        gcloud auth activate-service-account ${{ secrets.GCP_PF_SA }} --key-file=/tmp/credentials.json
-        kubectl config view
-        ls -la /tmp
-      #   KUBECONFIG: /tmp/kube_config
-      #   KUBE_CONFIG_PATH: /tmp/kube_config
-    - name: Run Kitchen
-      run: kitchen test
-      env:
-        TF_VAR_billing_account: ${{ secrets.GCP_BILLING_ACCOUNT }}
-        TF_VAR_org_id: ${{ secrets.GCP_ORG_ID }}
-        TF_VAR_folder_id: ${{ secrets.GCP_CCV_CI_FOLDER_ID }}
-        INFOBLOX_USERNAME: ${{ secrets.INFOBLOX_JHUB_USER }}
-        INFOBLOX_PASSWORD: ${{ secrets.INFOBLOX_JHUB_PSWD }}
-        INFOBLOX_SERVER: ${{secrets.INFOBLOX_JHUB_HOST}}
-        TF_VAR_site_certificate_file: /tmp/tls.cer
-        TF_VAR_site_certificate_key_file: /tmp/tls.key
-        USE_GKE_GCLOUD_AUTH_PLUGIN: true
-        # KUBECONFIG: /tmp/kube_config
-        # KUBE_CONFIG_PATH: /tmp/kube_config
-    - name: Clean kitchen and terraform files
-      run: |
-        rm -rf .kitchen
-        rm -rf examples/*/.terraform
-        rm -rf examples/*/terraform.tfstate*
-        rm -f ~/.kube/config
-        ls -la ~/.kube || :
-    - name: Post-check dirty dirs in self-hosted
-      run: |
-        ls -la .
-        ls -la examples/sample-jhub
-        ls -la examples/sample-jhub-nfs
-        ls -la ~
+        pwd
+  #   - name: Remove Kitchen File
+  #     run: |
+  #       rm -rf .kitchen
+  #       rm -rf .terraform
+  #       rm -rf examples/*/.terraform
+  #       rm -rf examples/*/terraform.tfstate*
+  #       rm -f ~/.kube/config
+  #       ls -la ~/.kube || :
+  #   - name: Post-check dirty dirs in self-hosted
+  #     run: |
+  #       ls -la ~
+  #       ls -la .
+  #       ls -la examples/sample-jhub
+  #       ls -la examples/sample-jhub-nfs
+  #   - name: Create Credential File
+  #     run: |
+  #       echo "$GCP_CREDENTIAL_JSON" | base64 -d > /tmp/credentials.json
+  #     env:
+  #       GCP_CREDENTIAL_JSON: ${{ secrets.GCP_CREDENTIAL_JSON}}
+  #   - name: Create TLS Files
+  #     run: |
+  #       echo "$JUPYTERHUB_TLS_CER" > /tmp/tls.cer
+  #       echo "$JUPYTERHUB_TLS_KEY" > /tmp/tls.key
+  #     env:
+  #       JUPYTERHUB_TLS_CER: ${{ secrets.JUPYTERHUB_TLS_CER }}
+  #       JUPYTERHUB_TLS_KEY: ${{ secrets.JUPYTERHUB_TLS_KEY }}
+  #   - name: Authorize service account
+  #     run: | 
+  #       gcloud auth activate-service-account ${{ secrets.GCP_PF_SA }} --key-file=/tmp/credentials.json
+  #       kubectl config view
+  #       ls -la /tmp
+  #     #   KUBECONFIG: /tmp/kube_config
+  #     #   KUBE_CONFIG_PATH: /tmp/kube_config
+  #   - name: Run Kitchen
+  #     run: kitchen test
+  #     env:
+  #       TF_VAR_billing_account: ${{ secrets.GCP_BILLING_ACCOUNT }}
+  #       TF_VAR_org_id: ${{ secrets.GCP_ORG_ID }}
+  #       TF_VAR_folder_id: ${{ secrets.GCP_CCV_CI_FOLDER_ID }}
+  #       INFOBLOX_USERNAME: ${{ secrets.INFOBLOX_JHUB_USER }}
+  #       INFOBLOX_PASSWORD: ${{ secrets.INFOBLOX_JHUB_PSWD }}
+  #       INFOBLOX_SERVER: ${{secrets.INFOBLOX_JHUB_HOST}}
+  #       TF_VAR_site_certificate_file: /tmp/tls.cer
+  #       TF_VAR_site_certificate_key_file: /tmp/tls.key
+  #       USE_GKE_GCLOUD_AUTH_PLUGIN: true
+  #       # KUBECONFIG: /tmp/kube_config
+  #       # KUBE_CONFIG_PATH: /tmp/kube_config
+  #   - name: Clean kitchen and terraform files
+  #     run: |
+  #       rm -rf .kitchen
+  #       rm -rf examples/*/.terraform
+  #       rm -rf examples/*/terraform.tfstate*
+  #       rm -f ~/.kube/config
+  #       ls -la ~/.kube || :
+  #   - name: Post-check dirty dirs in self-hosted
+  #     run: |
+  #       ls -la .
+  #       ls -la examples/sample-jhub
+  #       ls -la examples/sample-jhub-nfs
+  #       ls -la ~
   
-  # Clean up dangling images in self-hosted runner to avoid filling up docker disk 
-  docker-cleanup:
-    needs: [test]
-    runs-on: self-hosted 
-    steps:
-    - name: Clean up docker images
-      run: |
-        docker images --filter=reference='brownccv/kitchen-terraform'
-        docker images --filter=reference='brownccv/kitchen-terraform' --filter "dangling=true" | grep -E "brownccv/kitchen-terraform" | awk '{ print $3 }' | xargs docker rmi || :
-        echo "After cleanup"
-        docker images --filter=reference='brownccv/kitchen-terraform'
+  # # Clean up dangling images in self-hosted runner to avoid filling up docker disk 
+  # docker-cleanup:
+  #   needs: [test]
+  #   runs-on: self-hosted 
+  #   steps:
+  #   - name: Clean up docker images
+  #     run: |
+  #       docker images --filter=reference='brownccv/kitchen-terraform'
+  #       docker images --filter=reference='brownccv/kitchen-terraform' --filter "dangling=true" | grep -E "brownccv/kitchen-terraform" | awk '{ print $3 }' | xargs docker rmi || :
+  #       echo "After cleanup"
+  #       docker images --filter=reference='brownccv/kitchen-terraform'
